apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:          # <-- ADD THIS LINE
      - name: dockerhub-secret   # <-- AND THIS LINE
      containers:
      - name: mypythondockerrepo
       # image: kumarpm/mypythondockerrepo:latest
        image: pratikdevopsacr.azurecr.io/mypythondockerrepo:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
